server:
  port: 7080
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jhanrq8888/DAD-2024.git
          searchPaths: config-data
          #username:
          #password:
          default-label: jhenderson
  security:
    user:
      name: root
      password: 123456