server:
  # port: 8085  # Se podría especificar un puerto fijo aquí, pero está comentado.
  port: ${PORT:${SERVER_PORT:0}}
  # El puerto del servidor se asigna dinámicamente a partir de las variables de entorno. Si no están definidas, será 0 (puerto aleatorio).

eureka:
  client:
    serviceUrl:
      # defaultZone: http://localhost:8090/eureka  # Se ha comentado para usar la variable de entorno.
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
      # La URL de Eureka se toma de la variable de entorno `EUREKA_URI`, y si no está definida, se utiliza `localhost:8090/eureka`.

  instance:
    # hostname: localhost  # La configuración del hostname se ha comentado.
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # Genera dinámicamente un `instance-id` para registrar la instancia en Eureka, usando el nombre de la aplicación y un valor aleatorio.

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          # Habilita el descubrimiento dinámico de rutas basadas en los servicios registrados en Eureka (utiliza `lb://` para balanceo de carga).

      routes:
        - id: ms-catalogo-service
          uri: lb://ms-catalogo-service  # Ruta para el servicio ms-catalogo-service
          predicates:
            - Path=/category/**  # Rutas que comienzan con `/category/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización (asumiblemente personalizado).

        - id: ms-auth-service
          uri: lb://ms-auth-service  # Ruta para el servicio de autenticación
          predicates:
            - Path=/auth/**  # Rutas que comienzan con `/auth/` se enrutan a este servicio.

        - id: ms-producto-service
          uri: lb://ms-producto-service  # Ruta para el servicio ms-producto-service
          predicates:
            - Path=/product/**  # Rutas que comienzan con `/product/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización.

        - id: ms-envio-service
          uri: lb://ms-envio-service  # Ruta para el servicio ms-envio-service
          predicates:
            - Path=/envio/**  # Rutas que comienzan con `/envio/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización.

        - id: ms-proveedor-service
          uri: lb://ms-proveedor-service  # Ruta para el servicio ms-proveedor-service
          predicates:
            - Path=/proveedor/**  # Rutas que comienzan con `/proveedor/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización.

        - id: ms-pedido-service
          uri: lb://ms-pedido-service  # Ruta para el servicio ms-pedido-service
          predicates:
            - Path=/pedido/**  # Rutas que comienzan con `/pedido/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización.

        - id: ms-inventario-service
          uri: lb://ms-inventario-service  # Ruta para el servicio ms-inventario-service
          predicates:
            - Path=/inventario/**  # Rutas que comienzan con `/inventario/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización.

        - id: ms-cliente-service
          uri: lb://ms-cliente-service  # Ruta para el servicio ms-cliente-service
          predicates:
            - Path=/cliente/**  # Rutas que comienzan con `/cliente/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización.

        - id: ms-pago-service
          uri: lb://ms-pago-service  # Ruta para el servicio ms-pago-service
          predicates:
            - Path=/pago/**  # Rutas que comienzan con `/pago/` se enrutan a este servicio.
          filters:
            - AuthFilter  # Filtro de autorización.



